### ISSUE TITLE
Can you provide code related to '3.2 Postmenstrual age prediction from the cortical surface'?

### ISSUE THREAD

**Issue by ContestantsD** [sukjulian/lab-gatr#2]
As title，i would like use your code as a baseline method to address some issues in cortical-related problems, can you release some 
template code ? thank you very much!

**Comment by sukjulian** [comment]
Hi! I am currently working on including the experiment-related setup. If it is urgent, feel free to send me an [e-mail](mailto:j.m.suk@utwente.nl) and I can send you some code snippets.
